from __future__ import annotations

ANALYSIS_SPEC_FIELDS = frozenset({
    "method",
    "analysis_id",
    "columns",
    "x_column",
    "y_column",
    "outcome_column",
    "group_column",
    "groups",
    "permutations",
    "seed",
    "study_design",
    "pair_column",
    "unit_column",
    "covariate_columns",
    "bootstrap_resamples",
    "confidence_level",
    "missing_data_policy",
    "purpose",
    "estimand",
    "contrast_definition",
    "claim_ceiling",
    "parameters",
    "hypothesis_column",
    "p_value_column",
    "family_name",
    "family_hypothesis_ids",
    "alpha",
})
